# Generated by Django 4.1.5 on 2023-01-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('credit_hours', models.IntegerField()),
                ('depatment', models.CharField(choices=[(1, 'CS'), (2, 'IT'), (3, 'IS'), (4, 'SE')], max_length=2)),
                ('total_students', models.IntegerField()),
            ],
        ),
    ]
