# Generated by Django 4.1.5 on 2023-01-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
